"""add

Revision ID: c83f9085db26
Revises: 7494ace7207a
Create Date: 2025-04-03 08:49:59.193712

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c83f9085db26'
down_revision = '7494ace7207a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qrcode', sa.Column('client_group_id', sa.Uuid(), nullable=True))
    op.add_column('qrcode', sa.Column('visit_id', sa.Uuid(), nullable=True))
    op.add_column('qrcode', sa.Column('is_used', sa.Boolean(), nullable=True))
    op.add_column('qrcode', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('qrcode', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'qrcode', 'clientgroup', ['client_group_id'], ['id'])
    op.create_foreign_key(None, 'qrcode', 'visit', ['visit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qrcode', type_='foreignkey')
    op.drop_constraint(None, 'qrcode', type_='foreignkey')
    op.alter_column('qrcode', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('qrcode', 'created_at')
    op.drop_column('qrcode', 'is_used')
    op.drop_column('qrcode', 'visit_id')
    op.drop_column('qrcode', 'client_group_id')
    # ### end Alembic commands ###
