"""add

Revision ID: f35f4dcefe53
Revises: 379d4906a0c5
Create Date: 2025-04-03 11:39:40.070364

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f35f4dcefe53'
down_revision = '379d4906a0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('visit_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'payment', 'visit', ['visit_id'], ['id'])
    op.add_column('visit', sa.Column('payment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'visit', 'payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visit', type_='foreignkey')
    op.drop_column('visit', 'payment_id')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'visit_id')
    # ### end Alembic commands ###
